version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      docker: 19
  pre_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
      - docker build -t zen-hackaton . -f ./Dockerfile.app
  post_build:
    commands:
      - echo Build completed on `date`