name: Create Review App

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build-image:
    name: "Build Docker Images"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: "npm run clean install"
      run: npm ci
    - name: "build docker"
      run: docker build -t app-demo:${{ github.event.number }} -f ./Dockerfile.api
    # - run: npm run clean
